import { Craft } from './types';

export const crafts: Craft[] = [
  {
    id: 'ten-lua-tai-che',
    name: 'Tên Lửa Tái Chế',
    emoji: '🚀',
    description: 'Tên lửa siêu ngầu từ chai nhựa, cánh làm từ ống hút, nắp chai làm cửa sổ phi hành gia!',
    difficulty: 2,
    ageMin: 8,
    timeMinutes: 30,
    materials: [
      { materialId: 'chai-nhua', quantity: 2, sizePreference: 'Vừa (500ml)' },
      { materialId: 'ong-hut', quantity: 4 },
      { materialId: 'nap-chai', quantity: 3 },
    ],
    tools: ['Kéo', 'Keo dán', 'Băng keo', 'Bút lông'],
    steps: [
      { number: 1, title: 'Chuẩn bị thân tên lửa', detail: 'Rửa sạch 1 chai nhựa lớn, lau khô. Đây là thân tên lửa chính.' },
      { number: 2, title: 'Cắt cánh tên lửa', detail: 'Cắt chai nhựa thứ 2 thành 4 miếng hình tam giác. Đây là cánh ổn định.', tip: 'Nhờ người lớn giúp khi dùng kéo cắt nhựa cứng!' },
      { number: 3, title: 'Gắn cánh vào thân', detail: 'Dùng keo dán gắn 4 cánh đều quanh đáy chai. Đợi keo khô 5 phút.', tip: 'Dán đối xứng 2 cánh trước, rồi 2 cánh còn lại.' },
      { number: 4, title: 'Làm đầu tên lửa', detail: 'Cuộn giấy thành hình nón, dán lên nắp chai. Gắn nón lên đầu chai.' },
      { number: 5, title: 'Trang trí & hoàn thiện', detail: 'Dán nắp chai làm cửa sổ phi hành gia. Dùng bút lông vẽ họa tiết. Gắn ống hút làm ăng-ten.' },
    ],
    modelPath: '/models/ten-lua.glb',
    isShowcase: true,
  },
  {
    id: 'chau-hoa-mini',
    name: 'Chậu Hoa Mini',
    emoji: '🌸',
    description: 'Chậu hoa xinh xắn từ chai nhựa cắt đôi, trang trí bằng nắp chai nhiều màu!',
    difficulty: 1,
    ageMin: 6,
    timeMinutes: 20,
    materials: [
      { materialId: 'chai-nhua', quantity: 1, sizePreference: 'Vừa (500ml)' },
      { materialId: 'nap-chai', quantity: 5 },
    ],
    tools: ['Kéo', 'Sơn', 'Bút lông'],
    steps: [
      { number: 1, title: 'Cắt chai nhựa', detail: 'Cắt ngang chai nhựa ở giữa. Giữ lại phần dưới làm chậu.', tip: 'Nhờ người lớn giúp cắt nhựa!' },
      { number: 2, title: 'Tạo hình răng cưa', detail: 'Cắt mép trên thành hình zigzag hoặc cánh hoa.' },
      { number: 3, title: 'Sơn và trang trí', detail: 'Sơn phần ngoài chậu bằng màu yêu thích. Đợi khô 15 phút.' },
      { number: 4, title: 'Dán nắp chai trang trí', detail: 'Dán nắp chai nhiều màu xung quanh chậu tạo họa tiết.' },
      { number: 5, title: 'Hoàn thiện', detail: 'Đục vài lỗ nhỏ ở đáy để thoát nước. Có thể trồng cây nhỏ vào!' },
    ],
    modelPath: '/models/chau-hoa.glb',
    isShowcase: true,
  },
  {
    id: 'robot-hop-giay',
    name: 'Robot Hộp Giấy',
    emoji: '🤖',
    description: 'Robot siêu cool từ thùng carton, mắt bằng nắp chai, tay chân bằng lõi giấy!',
    difficulty: 3,
    ageMin: 10,
    timeMinutes: 45,
    materials: [
      { materialId: 'thung-carton', quantity: 2, sizePreference: 'Vừa' },
      { materialId: 'nap-chai', quantity: 4 },
      { materialId: 'loi-giay', quantity: 2 },
    ],
    tools: ['Kéo', 'Keo dán', 'Bút lông'],
    steps: [
      { number: 1, title: 'Chuẩn bị thân robot', detail: 'Lấy thùng carton vừa làm thân. Dán kín các mép bằng băng keo.' },
      { number: 2, title: 'Làm đầu robot', detail: 'Dùng thùng carton nhỏ hơn làm đầu. Gắn lên thân bằng keo dán.' },
      { number: 3, title: 'Gắn mắt và miệng', detail: 'Dán 2 nắp chai làm mắt. Vẽ miệng bằng bút lông.', tip: 'Dùng nắp chai màu khác nhau cho sinh động!' },
      { number: 4, title: 'Làm tay chân', detail: 'Cắt lõi giấy làm đôi. Gắn 2 cái làm tay, 2 cái làm chân.' },
      { number: 5, title: 'Thêm chi tiết', detail: 'Dán nắp chai còn lại làm nút bấm trên bụng. Vẽ thêm họa tiết.' },
      { number: 6, title: 'Trang trí hoàn thiện', detail: 'Sơn hoặc dán giấy màu bên ngoài. Gắn ăng-ten bằng ống hút nếu muốn.' },
    ],
    modelPath: '/models/robot.glb',
    isShowcase: true,
  },
  {
    id: 'ong-nhom-phieu-luu',
    name: 'Ống Nhòm Phiêu Lưu',
    emoji: '🔭',
    description: 'Ống nhòm thám hiểm từ 2 lõi giấy, dây đeo bằng ruy băng!',
    difficulty: 1,
    ageMin: 6,
    timeMinutes: 15,
    materials: [
      { materialId: 'loi-giay', quantity: 2, sizePreference: 'Lõi giấy vệ sinh' },
      { materialId: 'day-ruy-bang', quantity: 1 },
    ],
    tools: ['Kéo', 'Keo dán', 'Bút lông'],
    steps: [
      { number: 1, title: 'Dán 2 lõi giấy lại', detail: 'Xếp 2 lõi giấy song song, dán chặt bằng keo dán.' },
      { number: 2, title: 'Trang trí ống nhòm', detail: 'Dùng bút lông vẽ camo hoặc họa tiết yêu thích lên ống.' },
      { number: 3, title: 'Gắn dây đeo', detail: 'Đục lỗ 2 bên ngoài, luồn dây ruy băng qua làm dây đeo cổ.', tip: 'Đo dây vừa với cổ trước khi cắt!' },
      { number: 4, title: 'Hoàn thiện', detail: 'Thử đeo và nhìn qua ống nhòm. Điều chỉnh dây nếu cần.' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'xe-dua-chai-nhua',
    name: 'Xe Đua Chai Nhựa',
    emoji: '🏎️',
    description: 'Xe đua tốc độ từ chai nhựa, bánh xe bằng nắp chai, trục bằng đũa gỗ!',
    difficulty: 2,
    ageMin: 8,
    timeMinutes: 35,
    materials: [
      { materialId: 'chai-nhua', quantity: 1, sizePreference: 'Vừa (500ml)' },
      { materialId: 'nap-chai', quantity: 4 },
      { materialId: 'dua-go', quantity: 2, sizePreference: 'Đũa dài' },
    ],
    tools: ['Kéo', 'Keo dán'],
    steps: [
      { number: 1, title: 'Chuẩn bị thân xe', detail: 'Đặt chai nhựa nằm ngang. Đây là thân xe đua.' },
      { number: 2, title: 'Đục lỗ gắn trục', detail: 'Đục 4 lỗ trên chai — 2 gần đầu, 2 gần đáy — để xuyên đũa qua.', tip: 'Nhờ người lớn giúp đục lỗ!' },
      { number: 3, title: 'Gắn trục bánh xe', detail: 'Xuyên 2 đũa gỗ qua các lỗ làm trục trước và trục sau.' },
      { number: 4, title: 'Gắn bánh xe', detail: 'Dán 4 nắp chai vào 4 đầu đũa làm bánh xe. Đợi keo khô.' },
      { number: 5, title: 'Trang trí xe đua', detail: 'Vẽ số xe, sọc trang trí. Cắt giấy làm cánh gió phía sau nếu muốn.' },
    ],
    modelPath: '/models/xe-dua.glb',
    isShowcase: true,
  },
  {
    id: 'heo-tiet-kiem',
    name: 'Heo Tiết Kiệm',
    emoji: '🐷',
    description: 'Heo đất tiết kiệm siêu dễ thương từ chai nhựa, chân bằng nắp chai!',
    difficulty: 2,
    ageMin: 7,
    timeMinutes: 30,
    materials: [
      { materialId: 'chai-nhua', quantity: 1, sizePreference: 'Vừa (500ml)' },
      { materialId: 'giay-bao', quantity: 1 },
      { materialId: 'nap-chai', quantity: 4 },
    ],
    tools: ['Kéo', 'Keo dán', 'Sơn'],
    steps: [
      { number: 1, title: 'Chuẩn bị thân heo', detail: 'Đặt chai nhựa nằm ngang. Rửa sạch và lau khô.' },
      { number: 2, title: 'Bọc giấy báo', detail: 'Xé giấy báo thành miếng nhỏ. Dán phủ kín chai bằng hồ dán. Đợi khô.' },
      { number: 3, title: 'Gắn 4 chân', detail: 'Dán 4 nắp chai vào mặt dưới chai làm 4 chân heo.' },
      { number: 4, title: 'Sơn và vẽ mặt', detail: 'Sơn toàn thân màu hồng. Vẽ mắt, mũi (nắp chai), tai bằng giấy cắt.' },
      { number: 5, title: 'Cắt khe bỏ tiền', detail: 'Cắt 1 khe dài trên lưng heo để bỏ tiền xu vào.', tip: 'Nhờ người lớn giúp cắt khe bằng dao!' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'chuong-gio',
    name: 'Chuông Gió',
    emoji: '🎐',
    description: 'Chuông gió du dương từ lon nước, treo bằng dây ruy băng trên đũa gỗ!',
    difficulty: 1,
    ageMin: 7,
    timeMinutes: 25,
    materials: [
      { materialId: 'lon-nuoc', quantity: 3 },
      { materialId: 'day-ruy-bang', quantity: 1, sizePreference: 'Hẹp' },
      { materialId: 'dua-go', quantity: 1, sizePreference: 'Đũa dài' },
    ],
    tools: ['Kéo', 'Búa nhỏ (đục lỗ lon)'],
    steps: [
      { number: 1, title: 'Đục lỗ trên lon', detail: 'Dùng búa nhỏ và đinh đục 1 lỗ trên đáy mỗi lon.', tip: 'Bước này cần người lớn giúp — cẩn thận mép lon sắc!' },
      { number: 2, title: 'Luồn dây qua lon', detail: 'Cắt 3 đoạn dây ruy băng dài khác nhau. Luồn qua lỗ mỗi lon, thắt nút bên trong.' },
      { number: 3, title: 'Gắn vào đũa gỗ', detail: 'Buộc 3 đầu dây còn lại vào đũa gỗ, cách đều nhau.' },
      { number: 4, title: 'Trang trí', detail: 'Vẽ hoặc dán sticker lên lon. Buộc thêm dây ruy băng trang trí.' },
      { number: 5, title: 'Treo lên', detail: 'Buộc thêm 1 dây ở giữa đũa để treo. Treo nơi có gió nhẹ.' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'buom-loi-giay',
    name: 'Bướm Lõi Giấy',
    emoji: '🦋',
    description: 'Bướm xinh đẹp từ lõi giấy, cánh bằng giấy báo gấp, trang trí vải vụn!',
    difficulty: 1,
    ageMin: 6,
    timeMinutes: 20,
    materials: [
      { materialId: 'loi-giay', quantity: 1, sizePreference: 'Lõi giấy vệ sinh' },
      { materialId: 'giay-bao', quantity: 1, sizePreference: 'Tờ lớn' },
      { materialId: 'vai-vun', quantity: 1 },
    ],
    tools: ['Kéo', 'Keo dán', 'Bút lông'],
    steps: [
      { number: 1, title: 'Làm thân bướm', detail: 'Sơn hoặc bọc lõi giấy bằng vải vụn làm thân bướm.' },
      { number: 2, title: 'Cắt cánh bướm', detail: 'Gấp giấy báo đôi, cắt hình cánh bướm lớn. Mở ra được 2 cánh đối xứng.' },
      { number: 3, title: 'Gắn cánh vào thân', detail: 'Kẹp hoặc dán cánh giấy vào giữa lõi giấy.' },
      { number: 4, title: 'Trang trí cánh', detail: 'Vẽ hoa văn lên cánh bằng bút lông. Dán thêm vải vụn tạo điểm nhấn.' },
      { number: 5, title: 'Làm râu bướm', detail: 'Cắt 2 sợi giấy mỏng, uốn cong, dán lên đầu lõi giấy làm râu.' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'binh-hoa-thuy-tinh',
    name: 'Bình Hoa Thủy Tinh',
    emoji: '🌺',
    description: 'Bình hoa lung linh từ chai thủy tinh, trang trí bằng dây ruy băng và vải vụn!',
    difficulty: 1,
    ageMin: 8,
    timeMinutes: 20,
    materials: [
      { materialId: 'chai-thuy-tinh', quantity: 1, sizePreference: 'Lớn' },
      { materialId: 'day-ruy-bang', quantity: 1, sizePreference: 'Rộng' },
      { materialId: 'vai-vun', quantity: 1 },
    ],
    tools: ['Kéo', 'Keo dán'],
    steps: [
      { number: 1, title: 'Rửa sạch chai', detail: 'Rửa sạch chai thủy tinh, bóc hết nhãn dán. Lau khô hoàn toàn.' },
      { number: 2, title: 'Quấn ruy băng', detail: 'Quấn dây ruy băng quanh thân chai từ dưới lên, dán cố định bằng keo.' },
      { number: 3, title: 'Trang trí vải vụn', detail: 'Cắt vải vụn thành hình hoa hoặc lá. Dán lên chai tạo điểm nhấn.' },
      { number: 4, title: 'Thắt nơ cổ chai', detail: 'Thắt 1 nơ ruy băng ở cổ chai. Cắt đầu dây cho gọn.' },
      { number: 5, title: 'Hoàn thiện', detail: 'Có thể cắm hoa giấy hoặc hoa khô vào bình. Đặt trang trí bàn học!' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'khung-anh-vo-trung',
    name: 'Khung Ảnh Vỏ Trứng',
    emoji: '🖼️',
    description: 'Khung ảnh mosaic độc đáo từ vỏ trứng nghiền, trang trí trên thùng carton!',
    difficulty: 2,
    ageMin: 7,
    timeMinutes: 30,
    materials: [
      { materialId: 'vo-trung', quantity: 5, sizePreference: 'Trứng gà' },
      { materialId: 'thung-carton', quantity: 1, sizePreference: 'Nhỏ' },
      { materialId: 'giay-bao', quantity: 1 },
    ],
    tools: ['Kéo', 'Keo dán', 'Sơn', 'Bút lông'],
    steps: [
      { number: 1, title: 'Làm khung từ carton', detail: 'Cắt thùng carton thành hình chữ nhật. Cắt ô vuông ở giữa làm khung ảnh.' },
      { number: 2, title: 'Chuẩn bị vỏ trứng', detail: 'Rửa sạch vỏ trứng, bóc lớp màng trong. Để khô rồi bẻ thành miếng nhỏ.' },
      { number: 3, title: 'Dán vỏ trứng lên khung', detail: 'Phết keo lên khung carton. Dán từng miếng vỏ trứng tạo hoa văn mosaic.', tip: 'Dán từng miếng nhỏ sát nhau, để khe hở đều nhau cho đẹp!' },
      { number: 4, title: 'Sơn và tô màu', detail: 'Đợi keo khô. Sơn màu lên vỏ trứng hoặc để nguyên màu trắng tự nhiên.' },
      { number: 5, title: 'Gắn chân đứng', detail: 'Gấp 1 miếng carton nhỏ làm chân đỡ phía sau. Dán chắc bằng keo.' },
      { number: 6, title: 'Hoàn thiện', detail: 'Lót giấy báo phía sau để giữ ảnh. Đặt ảnh yêu thích vào khung!' },
    ],
    modelPath: null,
    isShowcase: false,
  },
  {
    id: 'den-loi-giay',
    name: 'Đèn Lồng Lõi Giấy',
    emoji: '🏮',
    description: 'Đèn lồng xinh xắn từ lõi giấy, trang trí bằng giấy báo và ống hút!',
    difficulty: 2,
    ageMin: 8,
    timeMinutes: 25,
    materials: [
      { materialId: 'loi-giay', quantity: 1, sizePreference: 'Lõi giấy bếp' },
      { materialId: 'giay-bao', quantity: 1, sizePreference: 'Tờ lớn' },
      { materialId: 'ong-hut', quantity: 2 },
      { materialId: 'day-ruy-bang', quantity: 1 },
    ],
    tools: ['Kéo', 'Keo dán', 'Bút lông'],
    steps: [
      { number: 1, title: 'Cắt lõi giấy', detail: 'Cắt dọc lõi giấy bếp thành các dải đều nhau, không cắt đứt hẳn ở 2 đầu.' },
      { number: 2, title: 'Tạo hình đèn lồng', detail: 'Ấn nhẹ 2 đầu lõi giấy vào nhau — các dải sẽ phồng ra thành hình đèn lồng.' },
      { number: 3, title: 'Bọc giấy báo bên ngoài', detail: 'Cắt giấy báo theo kích thước, dán bọc bên ngoài đèn lồng cho chắc.' },
      { number: 4, title: 'Gắn quai treo', detail: 'Đục 2 lỗ ở đầu trên, xỏ ống hút hoặc dây ruy băng làm quai treo.' },
      { number: 5, title: 'Trang trí', detail: 'Vẽ hoa văn bằng bút lông. Gắn thêm dây ruy băng tua rua ở đáy.' },
    ],
    modelPath: null,
    isShowcase: false,
  },
];
