import { GoogleGenerativeAI } from '@google/generative-ai';

const GEMINI_MODEL = 'gemini-2.0-flash-exp';

export async function generateImage(prompt: string): Promise<Buffer> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) throw new Error('GEMINI_API_KEY not configured');

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({
    model: GEMINI_MODEL,
    generationConfig: {
      responseModalities: ['image', 'text'],
    } as Record<string, unknown>,
  });

  const response = await model.generateContent(prompt);

  for (const part of response.response.candidates?.[0]?.content?.parts || []) {
    const p = part as unknown as Record<string, unknown>;
    if (p.inlineData) {
      const inlineData = p.inlineData as {
        mimeType: string;
        data: string;
      };
      if (inlineData.mimeType.startsWith('image/')) {
        return Buffer.from(inlineData.data, 'base64');
      }
    }
  }

  throw new Error('No image generated by Gemini');
}
