import { Material } from './types';

export const materials: Material[] = [
  { id: 'chai-nhua', name: 'Chai nhựa', emoji: '🧴', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/chai-nhua.glb', sizeOptions: ['Lớn (1.5L)', 'Vừa (500ml)', 'Nhỏ (330ml)'], category: 'plastic', funFact: 'Mỗi năm Việt Nam thải ra khoảng 1.8 triệu tấn rác nhựa. Một chai nhựa mất 450 năm để phân hủy trong tự nhiên — nhưng chỉ cần 5 phút để biến nó thành đồ chơi!' },
  { id: 'ong-hut', name: 'Ống hút', emoji: '🥤', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/ong-hut.glb', sizeOptions: ['Nhựa thường', 'Giấy', 'Inox'], category: 'plastic', funFact: 'Mỗi ngày thế giới sử dụng khoảng 500 triệu ống hút nhựa — đủ quấn quanh Trái Đất 2.5 vòng! Ống hút là một trong 10 loại rác phổ biến nhất trên bãi biển Việt Nam.' },
  { id: 'giay-bao', name: 'Giấy báo', emoji: '📰', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/giay-bao.glb', sizeOptions: ['Tờ lớn', 'Tờ nhỏ'], category: 'paper', funFact: 'Giấy báo phân hủy trong 2-6 tuần — nhanh hơn nhựa 10,000 lần! Ở Việt Nam, giấy báo cũ thường được dùng để gói xôi, gói hàng, và làm đồ thủ công.' },
  { id: 'lon-nuoc', name: 'Lon nước', emoji: '🥫', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/lon-nuoc.glb', sizeOptions: ['330ml', '250ml'], category: 'metal', funFact: 'Lon nhôm có thể tái chế vô hạn lần mà không giảm chất lượng. Tái chế 1 lon tiết kiệm đủ năng lượng để chạy TV trong 3 giờ!' },
  { id: 'nap-chai', name: 'Nắp chai', emoji: '🧢', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/nap-chai.glb', sizeOptions: ['Nắp nhựa', 'Nắp kim loại'], category: 'plastic', funFact: 'Nắp chai nhỏ nhưng nguy hiểm — chúng là một trong những thứ thường bị rùa biển và chim nuốt nhầm nhất. Ở Đà Nẵng có dự án thu gom nắp chai làm xe lăn cho người khuyết tật!' },
  { id: 'thung-carton', name: 'Thùng carton', emoji: '📦', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/thung-carton.glb', sizeOptions: ['Lớn', 'Vừa', 'Nhỏ'], category: 'paper', funFact: 'Thùng carton được phát minh năm 1817 ở Anh. Ở Việt Nam, nghề thu mua ve chai giúp tái chế hàng triệu tấn carton mỗi năm — một nghề rất quan trọng cho môi trường!' },
  { id: 'loi-giay', name: 'Lõi giấy', emoji: '🧻', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/loi-giay.glb', sizeOptions: ['Lõi giấy vệ sinh', 'Lõi giấy bếp'], category: 'paper', funFact: 'Một người trung bình dùng khoảng 100 cuộn giấy vệ sinh mỗi năm — tức là 100 lõi giấy có thể trở thành đồ chơi! Lõi giấy là vật liệu thủ công yêu thích của trẻ em toàn thế giới.' },
  { id: 'vai-vun', name: 'Vải vụn', emoji: '👕', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/vai-vun.glb', sizeOptions: ['Vải cotton', 'Vải tổng hợp'], category: 'fabric', funFact: 'Ngành dệt may là ngành gây ô nhiễm thứ 2 thế giới. Việt Nam là nước xuất khẩu dệt may lớn thứ 3 — rất nhiều vải vụn thừa có thể tái sử dụng thay vì vứt đi!' },
  { id: 'dua-go', name: 'Đũa gỗ', emoji: '🥢', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/dua-go.glb', sizeOptions: ['Đũa dài', 'Đũa ngắn'], category: 'wood', funFact: 'Mỗi năm Trung Quốc sử dụng 80 tỷ đôi đũa dùng một lần — tương đương 20 triệu cây bị chặt. Ở Việt Nam, đũa gỗ cũ có thể làm khung ảnh, mô hình, hoặc đồ chơi rất sáng tạo!' },
  { id: 'chai-thuy-tinh', name: 'Chai thủy tinh', emoji: '🍶', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/chai-thuy-tinh.glb', sizeOptions: ['Lớn', 'Nhỏ'], category: 'glass', funFact: 'Thủy tinh mất 1 triệu năm để phân hủy nhưng có thể tái chế 100% không giảm chất lượng. Chai thủy tinh cũ ở Việt Nam thường được tái sử dụng làm bình hoa hoặc đựng nước mắm!' },
  { id: 'day-ruy-bang', name: 'Dây ruy băng', emoji: '🎀', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/day-ruy-bang.glb', sizeOptions: ['Rộng', 'Hẹp'], category: 'fabric', funFact: 'Ruy băng có lịch sử hơn 3000 năm — từ thời Ai Cập cổ đại! Ở Việt Nam, ruy băng thường được dùng trang trí quà Tết và gói bánh trung thu.' },
  { id: 'vo-trung', name: 'Vỏ trứng', emoji: '🥚', modelPath: 'https://oxazgmvqiacyvbnviesf.supabase.co/storage/v1/object/public/models/materials/vo-trung.glb', sizeOptions: ['Trứng gà', 'Trứng vịt'], category: 'other', funFact: 'Vỏ trứng chứa 95% canxi cacbonat — cùng chất liệu với đá phấn! Ở Việt Nam, vỏ trứng nghiền nhỏ được nông dân dùng bón cây rất tốt. Và khi dán lên khung ảnh, chúng tạo hiệu ứng mosaic rất đẹp!' },
];
